//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notfy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacao
    {
        public int ID { get; set; }
        public int NotificandoID { get; set; }
        public int MatriculaImovel { get; set; }
        public int NotificadorID { get; set; }
        public Nullable<int> Sequencia { get; set; }
        public Nullable<System.DateTime> Tentativa1 { get; set; }
        public Nullable<System.DateTime> Tentativa2 { get; set; }
        public Nullable<System.DateTime> Tentativa3 { get; set; }
        public Nullable<bool> Concluido { get; set; }
        public string Observacao { get; set; }
    
        public virtual Notificador Notificador { get; set; }
        public virtual Notificando Notificando { get; set; }
    }
}
