//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notfy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Notificador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Notificador()
        {
            this.Notificacao = new HashSet<Notificacao>();
        }
    
        public int ID { get; set; }

        [Required(ErrorMessage = "É obrigatório informar o nome", AllowEmptyStrings = false)]
        public string Nome { get; set; }

        [Required(ErrorMessage = "É obrigatório informar o telefone", AllowEmptyStrings = false)]
        public string Telefone { get; set; }

        [Required(ErrorMessage = "É obrigatório informar o cpf", AllowEmptyStrings = false)]
        public string CPF { get; set; }

        [Required(ErrorMessage = "É obrigatório informar o email", AllowEmptyStrings = false)]
        public string Email { get; set; }
        public bool Tipo { get; set; }

        [Required(ErrorMessage = "É obrigatório informar o usuário", AllowEmptyStrings = false)]
        public string Usuario { get; set; }

        [Required(ErrorMessage = "É obrigatório informar a senha", AllowEmptyStrings = false)]
        public string Senha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificacao> Notificacao { get; set; }
    }
}
