CREATE DATABASE BD_NOTFY

USE BD_NOTFY
GO

CREATE TABLE Notificador(
ID INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR(255) NOT NULL,
Telefone VARCHAR(11) NOT NULL,
CPF VARCHAR (11) NOT NULL,
Email VARCHAR (150) NOT NULL,
Tipo BIT NOT NULL,
Usuario VARCHAR (60),
Senha VARCHAR(60)
)

CREATE TABLE Notificando(
ID INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR(255) NOT NULL,
Telefone VARCHAR(11) NOT NULL,
CPF VARCHAR (11) NOT NULL,
Email VARCHAR (150) NOT NULL,
Endereco VARCHAR (255) NOT NULL,
CEP VARCHAR(9) NOT NULL,
Cidade VARCHAR(255) NOT NULL,
Estado CHAR(2) NOT NULL
)

CREATE TABLE Notificacao(
ID INT PRIMARY KEY IDENTITY NOT NULL,
NotificandoID INT NOT NULL,
MatriculaImovel INT NOT NULL,
NotificadorID INT NOT NULL,
Sequencia INT,
Tentativa1 DATETIME,
Tentativa2 DATETIME,
Tentativa3 DATETIME,
Concluido TINYINT,
Observacao TEXT,
CONSTRAINT FK_notificandoID FOREIGN KEY (NotificandoID) REFERENCES Notificando (ID),
CONSTRAINT FK_notificadorID FOREIGN KEY (NotificadorID) REFERENCES Notificador (ID)
)


